import Head from "next/head";
import dbConnect from "lib/dbConnect";
import Product from "models/Product";
import Image from "next/image";
import ProductCard from "components/ProductCard";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Pre-Workout Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="">Pre-Workouts</h1>
        <div className="">
          <div className="grid gap-2 grid-flow-row grid-cols-4 grid-rows-3">
            {products.map((product, index) => (
              <ProductCard key={product._id} product={product} />
            ))}
          </div>
        </div>
      </div>
    </>
  );
}

export async function getServerSideProps() {
  try {
    await dbConnect();
    const products = await Product.find({}); // grab all pre-workout products
    return { props: { products: JSON.parse(JSON.stringify(products)) } };
  } catch (error) {
    console.error(error);
    // return empty array to ensure app doesnt crash and provides a fallback for rendering the page
    return { props: { products: [] } };
  }
}
